#!/usr/bin/env bash
set -euo pipefail
IMAGE="registry.digitalocean.com/jeff-starterkit-reg/doks-example"
TARGET="${IMAGE}:${DC}"

# If you are developing with Apple M1 series chipset, then you should specify the --platform=linux/amd64 
docker build --no-cache --platform=linux/amd64 -t ${TARGET} .
docker push ${TARGET}
