#!/usr/bin/env bash
set -euo pipefail
DC="$1"
CLUSTER="doks-${DC}-multi-region-cluster"
# echo ${CLUSTER}
# NODE_POOL="$(doctl kubernetes cluster node-pool list doks-syd1-multi-region-cluster --format Name --no-header)"
doctl compute load-balancer delete --force $(kubectl get svc doks-example -o jsonpath="{.metadata.annotations.kubernetes\.digitalocean\.com/load-balancer-id}")
# doctl kubernetes cluster node-pool delete --force ${CLUSTER} ${NODE_POOL}
doctl k8s cluster delete ${CLUSTER}


