#!/usr/bin/env bash
set -euo pipefail
DC="$1"
CLUSTER="doks-${DC}-multi-region-cluster"
SERVICE="doks-example"
REGISTRY="jeff-starterkit-reg"
# You need to change the registry name
IMAGE="registry.digitalocean.com/${REGISTRY}/doks-example"
TARGET="${IMAGE}:${DC}"
CONTEXT="do-${DC}-${CLUSTER}"
MANIFEST_FILE="manifest.yaml"
BACKUP_MANIFEST_FILE="manifest.yaml.bak"
doctl k8s cluster create ${CLUSTER} --region ${DC} --count 1

# Make a backup file for manifest.yaml
cp $MANIFEST_FILE $BACKUP_MANIFEST_FILE
sed -i '' "s|TARGET|${TARGET}|g" $MANIFEST_FILE


kubectl config set-context ${CONTEXT}
doctl registry kubernetes-manifest | kubectl apply -f -

kubectl --context ${CONTEXT} apply -f ${MANIFEST_FILE}
rm $MANIFEST_FILE
mv $BACKUP_MANIFEST_FILE $MANIFEST_FILE
script/wait-for-service ${CONTEXT} ${SERVICE}
open http://$(kubectl --context ${CONTEXT} get service ${SERVICE} --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")
